name: Docker Build and Push Nightly

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  schedule:
    - cron:  '5 1 * * 0'

env:
  DOCKER_USER: sumizadocker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: log into docker
      run: |
        docker logout
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USER --password-stdin
  
    - name: build and push all
      run: |
        
        # Alpine
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
        -f 3.12-alpine \
        -t $DOCKER_USER/${{ github.event.repository.name }}:3.12-alpine . --push

        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
        -f 3.13-alpine \
        -t $DOCKER_USER/${{ github.event.repository.name }}:3.13-alpine . --push


        # Regular
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
        -f 3.12 \
        -t $DOCKER_USER/${{ github.event.repository.name }}:3.12 . --push
        
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
        -f 3.13 \
        -t $DOCKER_USER/${{ github.event.repository.name }}:3.13 . --push

        
        # Slim
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
        -f 3.12-slim \
        -t $DOCKER_USER/${{ github.event.repository.name }}:3.12-slim . --push
        
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
        -f 3.13-slim \
        -t $DOCKER_USER/${{ github.event.repository.name }}:3.13-slim . --push


    - name: log out of docker
      run: docker logout
